global:
  scrape_interval: 15s #Каждые 15сек дергает API, чтоб понять работает ли

rule_files:
  - /etc/prometheus/rules.yml  #путь к правилам

scrape_configs: 
  - job_name: "blackbox" #пока только blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://app:8080/health #будет заходить на этот адрес проверять работоспособность сайта
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115 

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]