services:

  # База данных
  db:
    image: mariadb:11
    container_name: mariadb
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  # Приложение
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: url-shortener
    ports:
      - "8080:8080"
    env_file:
      - ./config/app.env
    depends_on:
      - db
    restart: unless-stopped

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"
    depends_on:
      - blackbox

  # Blackbox Exporter
  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox-exporter/blackbox.yml:/etc/blackbox_exporter/config.yml

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  # Alertmanager
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    env_file:
      - ./config/tg.env  
    volumes:
      - ./alerting/alertmanager.yml:/etc/alertmanager/alertmanager.yml

volumes:
  db_data: